services:
  - type: web
    name: campus-job-board-api
    env: python
    plan: free
    rootDir: django_backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py bootstrap_deploy && gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false