# Generated by Django 5.1.7 on 2026-03-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('role', models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter'), ('lecturer', 'Lecturer'), ('admin', 'Admin')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('image_url', models.URLField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('age_range', models.CharField(blank=True, max_length=20)),
                ('about_me', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('program', models.CharField(blank=True, max_length=200)),
                ('student_number', models.CharField(blank=True, max_length=50)),
                ('work_experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('hobbies_interests', models.TextField(blank=True)),
                ('job_preference', models.CharField(blank=True, max_length=255)),
                ('resume_url', models.URLField(blank=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('fcm_token', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_description', models.TextField(blank=True)),
                ('company_website', models.URLField(blank=True)),
                ('company_location', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
